[package]
name = "rlib"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.22.2", features = ["extension-module"] }
rustypath = { version = "1.2.1", features = ["pyo3-bindings"] }

[lib]
crate-type = ["cdylib"]

[build-dependencies]
cc = "1.0"
