name: Build

on: [push]

jobs:
    Build:
        strategy:
            matrix:
                os: [macos-latest]
        
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Build Test
              uses: d33p0st/python-rust-mix-build@v4
              with:
                python-version: 3.12